#!/bin/bash

# $Header: /u/gcmpack/MITgcm/verification/solid-body.cs-32x32x1/input/Attic/genmake_local,v 1.1.2.1 2003/10/06 14:49:44 edhill Exp $

#  This is the local options file for the "new" version of genmake 
#
#  EH3 initial version 2003-08


DISABLE="aim gmredi kpp obcs zonal_filt"

ENABLE="shap_filt timeave"
