#!/bin/bash
#
#  $Header: /u/gcmpack/MITgcm/tools/build_options/linux_ia32_g77,v 1.1.2.1 2003/10/01 20:43:24 adcroft Exp $
#


FC=g77
DEFINES='-D_BYTESWAPIO -DWORDLENGTH=4'
LN='/bin/ln -s'
CPP='cpp  -traditional -P'
NOOPTFLAGS='-O0'

#  For IEEE, use the "-ffloat-store" option
if test "x$IEEE" = x ; then
    FFLAGS='-Wimplicit -Wunused -Wuninitialized'
    FOPTIM='-O3 -malign-double -funroll-loops'
else
    FFLAGS='-Wimplicit -Wunused -ffloat-store'
    FOPTIM='-O0 -malign-double'
fi



