#!/bin/bash

# $Header: /u/gcmpack/MITgcm/verification/aim.5l_LatLon/input/Attic/genmake_local,v 1.1.2.1 2003/10/06 14:49:43 edhill Exp $

#  This is the local options file for the "new" version of genmake 
#
#  EH3 initial version 2003-08

DISABLE="kpp gmredi obcs aim_v23"

ENABLE=aim
