#!/bin/bash

# $Header: /u/gcmpack/MITgcm/verification/global_with_exf/input/Attic/genmake_local,v 1.1.2.1 2003/10/06 14:49:44 edhill Exp $

#  This is the local options file for the "new" version of genmake 
#
#  EH3 initial version 2003-08

#DISABLE="obcs zonal_filt shap_filt"
DISABLE="obcs zonal_filt shap_filt kpp"

ENABLE="cal exf"

