#!/bin/bash

# $Header: /u/gcmpack/MITgcm/verification/natl_box/input/Attic/genmake_local,v 1.1.2.1 2003/10/06 14:49:44 edhill Exp $

#  This is the local options file for the "new" version of genmake 
#
#  EH3 initial version 2003-08


DISABLE="aim gmredi obcs zonal_filt"

ENABLE="kpp shap_filt timeave"
