#!/bin/bash

# $Header: /u/gcmpack/MITgcm/verification/aim.5l_cs/input/Attic/genmake_local,v 1.1.2.1 2003/10/06 14:49:43 edhill Exp $

#  This is the local options file for the "new" version of genmake 
#
#  EH3 initial version 2003-08

DISABLE="aim kpp gmredi obcs mom_fluxform zonal_filt"

ENABLE=aim_v23
